spring:
  data:
    mongodb:
      username: user
      password: 123456
      uri: mongodb://47.102.201.46:27017/admin
      port: 27017

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true