spring:
  data:
    mongodb:
#      username: user
#      password: 123456
#      uri: mongodb://47.102.201.46:27017/admin
#      uri: mongodb://121.41.227.134:27017/admin
      uri: mongodb://localhost:27017/admin
      port: 27017

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    swagger:
      ebable:true